using System;
using System.Linq;
using QuickTranslate.Models;

namespace QuickTranslate.Helpers;

public static class LanguageData
{
    private static readonly LanguageOption[] AllLanguages =
    [
        new("Afar", "aa"),
        new("Abkhazian", "ab"),
        new("Avestan", "ae"),
        new("Afrikaans", "af"),
        new("Akan", "ak"),
        new("Amharic", "am"),
        new("Aragonese", "an"),
        new("Arabic", "ar"),
        new("Assamese", "as"),
        new("Avaric", "av"),
        new("Aymara", "ay"),
        new("Azerbaijani", "az"),
        new("Bashkir", "ba"),
        new("Belarusian", "be"),
        new("Bulgarian", "bg"),
        new("Bihari languages", "bh"),
        new("Bislama", "bi"),
        new("Bambara", "bm"),
        new("Bengali", "bn"),
        new("Tibetan", "bo"),
        new("Breton", "br"),
        new("Bosnian", "bs"),
        new("Catalan", "ca"),
        new("Chechen", "ce"),
        new("Chamorro", "ch"),
        new("Corsican", "co"),
        new("Cree", "cr"),
        new("Czech", "cs"),
        new("Church Slavic", "cu"),
        new("Chuvash", "cv"),
        new("Welsh", "cy"),
        new("Danish", "da"),
        new("German", "de"),
        new("Divehi", "dv"),
        new("Dzongkha", "dz"),
        new("Ewe", "ee"),
        new("Greek", "el"),
        new("English", "en"),
        new("Esperanto", "eo"),
        new("Spanish", "es"),
        new("Estonian", "et"),
        new("Basque", "eu"),
        new("Persian", "fa"),
        new("Fulah", "ff"),
        new("Finnish", "fi"),
        new("Fijian", "fj"),
        new("Faroese", "fo"),
        new("French", "fr"),
        new("Western Frisian", "fy"),
        new("Irish", "ga"),
        new("Scottish Gaelic", "gd"),
        new("Galician", "gl"),
        new("Guarani", "gn"),
        new("Gujarati", "gu"),
        new("Manx", "gv"),
        new("Hausa", "ha"),
        new("Hebrew", "he"),
        new("Hindi", "hi"),
        new("Hiri Motu", "ho"),
        new("Croatian", "hr"),
        new("Haitian", "ht"),
        new("Hungarian", "hu"),
        new("Armenian", "hy"),
        new("Herero", "hz"),
        new("Interlingua", "ia"),
        new("Indonesian", "id"),
        new("Interlingue", "ie"),
        new("Igbo", "ig"),
        new("Sichuan Yi", "ii"),
        new("Inupiaq", "ik"),
        new("Ido", "io"),
        new("Icelandic", "is"),
        new("Italian", "it"),
        new("Inuktitut", "iu"),
        new("Japanese", "ja"),
        new("Javanese", "jv"),
        new("Georgian", "ka"),
        new("Kongo", "kg"),
        new("Kikuyu", "ki"),
        new("Kuanyama", "kj"),
        new("Kazakh", "kk"),
        new("Kalaallisut", "kl"),
        new("Central Khmer", "km"),
        new("Kannada", "kn"),
        new("Korean", "ko"),
        new("Kanuri", "kr"),
        new("Kashmiri", "ks"),
        new("Kurdish", "ku"),
        new("Komi", "kv"),
        new("Cornish", "kw"),
        new("Kirghiz", "ky"),
        new("Latin", "la"),
        new("Luxembourgish", "lb"),
        new("Ganda", "lg"),
        new("Limburgish", "li"),
        new("Lingala", "ln"),
        new("Lao", "lo"),
        new("Lithuanian", "lt"),
        new("Luba-Katanga", "lu"),
        new("Latvian", "lv"),
        new("Malagasy", "mg"),
        new("Marshallese", "mh"),
        new("Maori", "mi"),
        new("Macedonian", "mk"),
        new("Malayalam", "ml"),
        new("Mongolian", "mn"),
        new("Marathi", "mr"),
        new("Malay", "ms"),
        new("Maltese", "mt"),
        new("Burmese", "my"),
        new("Nauru", "na"),
        new("Norwegian Bokmål", "nb"),
        new("North Ndebele", "nd"),
        new("Nepali", "ne"),
        new("Ndonga", "ng"),
        new("Dutch", "nl"),
        new("Norwegian Nynorsk", "nn"),
        new("Norwegian", "no"),
        new("South Ndebele", "nr"),
        new("Navajo", "nv"),
        new("Chichewa", "ny"),
        new("Occitan", "oc"),
        new("Ojibwa", "oj"),
        new("Oromo", "om"),
        new("Oriya", "or"),
        new("Ossetian", "os"),
        new("Panjabi", "pa"),
        new("Pali", "pi"),
        new("Polish", "pl"),
        new("Pashto", "ps"),
        new("Portuguese", "pt"),
        new("Quechua", "qu"),
        new("Romansh", "rm"),
        new("Rundi", "rn"),
        new("Romanian", "ro"),
        new("Russian", "ru"),
        new("Kinyarwanda", "rw"),
        new("Sanskrit", "sa"),
        new("Sardinian", "sc"),
        new("Sindhi", "sd"),
        new("Northern Sami", "se"),
        new("Sango", "sg"),
        new("Sinhala", "si"),
        new("Slovak", "sk"),
        new("Slovenian", "sl"),
        new("Samoan", "sm"),
        new("Shona", "sn"),
        new("Somali", "so"),
        new("Albanian", "sq"),
        new("Serbian", "sr"),
        new("Swati", "ss"),
        new("Southern Sotho", "st"),
        new("Sundanese", "su"),
        new("Swedish", "sv"),
        new("Swahili", "sw"),
        new("Tamil", "ta"),
        new("Telugu", "te"),
        new("Tajik", "tg"),
        new("Thai", "th"),
        new("Tigrinya", "ti"),
        new("Turkmen", "tk"),
        new("Tagalog", "tl"),
        new("Tswana", "tn"),
        new("Tonga", "to"),
        new("Turkish", "tr"),
        new("Tsonga", "ts"),
        new("Tatar", "tt"),
        new("Twi", "tw"),
        new("Tahitian", "ty"),
        new("Uighur", "ug"),
        new("Ukrainian", "uk"),
        new("Urdu", "ur"),
        new("Uzbek", "uz"),
        new("Venda", "ve"),
        new("Vietnamese", "vi"),
        new("Volapük", "vo"),
        new("Walloon", "wa"),
        new("Wolof", "wo"),
        new("Xhosa", "xh"),
        new("Yiddish", "yi"),
        new("Yoruba", "yo"),
        new("Zhuang", "za"),
        new("Chinese", "zh"),
        new("Zulu", "zu"),
    ];

    private static readonly string[] CommonLanguageCodes = [
        "en", "es", "fr", "de", "it", "pt", "ru",
        "ja", "ko", "zh", "ar", "hi", "tr", "nl", "pl"
    ];

    public static LanguageOption[] GetAll()
    {
        var common = AllLanguages.Where(l => CommonLanguageCodes.Contains(l.Code))
                                 .OrderBy(l => Array.IndexOf(CommonLanguageCodes, l.Code))
                                 .ToList();

        var others = AllLanguages.Where(l => !CommonLanguageCodes.Contains(l.Code))
                                 .OrderBy(l => l.DisplayName)
                                 .ToList();

        return [new LanguageOption("Auto-detect", "auto"), .. common, .. others];
    }
}
